MOCK_RANDOM_DATA = [
    {
        "id": 1,
        "first_name": "Floris",
        "last_name": "Ormerod",
        "email": "formerod0@dailymotion.com",
        "gender": "Female",
        "ip_address": "105.188.202.166",
        "database": "USER_DATA",
    },
    {
        "id": 2,
        "first_name": "Celestia",
        "last_name": "Daelman",
        "email": "cdaelman1@cargocollective.com",
        "gender": "Female",
        "ip_address": "110.206.54.26",
        "database": "USER_DATA",
    },
    {
        "id": 3,
        "first_name": "Berkie",
        "last_name": "Bankhurst",
        "email": "bbankhurst2@zdnet.com",
        "gender": "Non-binary",
        "ip_address": "15.182.23.37",
        "database": "USER_DATA",
    },
    {
        "id": 4,
        "first_name": "Jasmine",
        "last_name": "Wolledge",
        "email": "jwolledge3@chicagotribune.com",
        "gender": "Female",
        "ip_address": "23.150.218.156",
        "database": "USER_DATA",
    },
    {
        "id": 5,
        "first_name": "Bendick",
        "last_name": "Janikowski",
        "email": "bjanikowski4@newyorker.com",
        "gender": "Male",
        "ip_address": "40.153.200.35",
        "database": "USER_DATA",
    },
    {
        "id": 6,
        "bitcoin_address": "1Lr48QZEiGSfRDP1DUoKpCtWoPKNApZepD",
        "ip_address": "115.175.85.79",
        "car_vin": "5GADX33L26D025263",
        "email": "ddallman0@virginia.edu",
        "database": "RANDOM_DATA",
    },
    {
        "id": 7,
        "bitcoin_address": "143ejZzXUFUDjiaFGCW4kusgxKptGe3NNY",
        "ip_address": "242.239.23.181",
        "car_vin": "1G6DF577680964777",
        "email": "ahallatt1@nydailynews.com",
        "database": "RANDOM_DATA",
    },
    {
        "id": 8,
        "bitcoin_address": "1KvykXkAFVWSyRyAasACgvFRgNgWdM7GCZ",
        "ip_address": "211.87.121.89",
        "car_vin": "WAUUL58E35A012342",
        "email": "fguillot2@mac.com",
        "database": "RANDOM_DATA",
    },
    {
        "id": 9,
        "bitcoin_address": "13vNKeUSeHYVCFXusAd57MkkQvko5Ug9vT",
        "ip_address": "32.14.128.80",
        "car_vin": "JH4NA12645S359873",
        "email": "elace3@bizjournals.com",
        "database": "RANDOM_DATA",
    },
    {
        "id": 10,
        "bitcoin_address": "19JR55Fn5Usx9xSintCNuWm37M4nxw7oQq",
        "ip_address": "123.82.137.187",
        "car_vin": "5J6TF2H5XEL254919",
        "email": "tyouings4@paginegialle.it",
        "database": "RANDOM_DATA",
    },
]
